config/routes.rb
Rails.application.routes.draw do
  resources :lores
  resources :parasites
  resources :plants
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "plants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lore.rb
class Lore < ApplicationRecord
    validates_presence_of :title, :content, :image
end

app/models/parasite.rb
class Parasite < ApplicationRecord
    validates_presence_of :name, :description, :capacity, :pv, :atk, :def, :image
end

app/models/plant.rb
class Plant < ApplicationRecord
    validates_presence_of :name, :description, :capacity, :pv, :atk, :def, :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lores_controller.rb
class LoresController < ApplicationController
  before_action :set_lore, only: %i[ show edit update destroy ]

  # GET /lores or /lores.json
  def index
    @lores = Lore.all
  end

  # GET /lores/1 or /lores/1.json
  def show
  end

  # GET /lores/new
  def new
    @lore = Lore.new
  end

  # GET /lores/1/edit
  def edit
  end

  # POST /lores or /lores.json
  def create
    @lore = Lore.new(lore_params)

    respond_to do |format|
      if @lore.save
        format.html { redirect_to lore_url(@lore), notice: "Lore was successfully created." }
        format.json { render :show, status: :created, location: @lore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lores/1 or /lores/1.json
  def update
    respond_to do |format|
      if @lore.update(lore_params)
        format.html { redirect_to lore_url(@lore), notice: "Lore was successfully updated." }
        format.json { render :show, status: :ok, location: @lore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lores/1 or /lores/1.json
  def destroy
    @lore.destroy

    respond_to do |format|
      format.html { redirect_to lores_url, notice: "Lore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lore
      @lore = Lore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lore_params
      params.require(:lore).permit(:title, :content, :image)
    end
end

app/controllers/parasites_controller.rb
class ParasitesController < ApplicationController
  before_action :set_parasite, only: %i[ show edit update destroy ]

  # GET /parasites or /parasites.json
  def index
    @parasites = Parasite.all
  end

  # GET /parasites/1 or /parasites/1.json
  def show
  end

  # GET /parasites/new
  def new
    @parasite = Parasite.new
  end

  # GET /parasites/1/edit
  def edit
  end

  # POST /parasites or /parasites.json
  def create
    @parasite = Parasite.new(parasite_params)

    respond_to do |format|
      if @parasite.save
        format.html { redirect_to parasite_url(@parasite), notice: "Parasite was successfully created." }
        format.json { render :show, status: :created, location: @parasite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parasite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parasites/1 or /parasites/1.json
  def update
    respond_to do |format|
      if @parasite.update(parasite_params)
        format.html { redirect_to parasite_url(@parasite), notice: "Parasite was successfully updated." }
        format.json { render :show, status: :ok, location: @parasite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parasite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parasites/1 or /parasites/1.json
  def destroy
    @parasite.destroy

    respond_to do |format|
      format.html { redirect_to parasites_url, notice: "Parasite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parasite
      @parasite = Parasite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parasite_params
      params.require(:parasite).permit(:name, :description, :capacity, :pv, :atk, :def, :image)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: %i[ show edit update destroy ]

  # GET /plants or /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1 or /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants or /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully created." }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1 or /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to plant_url(@plant), notice: "Plant was successfully updated." }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1 or /plants/1.json
  def destroy
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to plants_url, notice: "Plant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :description, :capacity, :pv, :atk, :def, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lores_helper.rb
module LoresHelper
end

app/helpers/parasites_helper.rb
module ParasitesHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Terrarium</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-expand-lg ml-5 border-0 p-4 mb-5">
        <div class="container-fluid container">
            <%= image_tag 'logo.svg', class:"mx-auto img-fluid me-5", target:"#" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav w-100 d-flex justify-content-end">
              <%= link_to "Voir les plantes", plants_path, class:'me-5 mb-2 text-decoration-none  text-black text-custom link-primary' %>
              <%= link_to "Voir les parasites", parasites_path, class:'me-5 mb-2 text-decoration-none text-black link-primary' %>
              <%= link_to "En apprendre plus sur ce monde", lores_path, class:'me-5 mb-2 text-decoration-none text-black link-primary' %>
            </div>
          </div>
        </div>
    </nav>
    <div class="container mb-5">
      <h3 class="w-100 text-left border-start border-5 border-success p-3"><em>Terrarium, 3043 </em>: les humains peinent à garder leur place dans ce monde. Des siècles de pollution, de destruction, ont changé et refaçonné la planète 
      Terre. La végétation a repris le dessus, a évolué, s'est transformée afin de survivre et, de cette évolution sont nés les Monstres-Plantes.<br>
      Venez découvrir Terrarium, un monde en ruines.
      </h3>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <div class="container text-center mb-3">
  <div class="row">
    <div class="col">
      <p class="text-secondary">©2023 - All rights reserved<br>
      Made with : Ruby on Rails, Bootstrap, Midjourney<br>
      <a href="https://www.linkedin.com/in/coralie-alexandru-0a57391b9/" target="_blank" class="text-decoration-none text-black link-primary">ALEXANDRU Coralie</a>, <a href="https://www.linkedin.com/in/tstranquang/" target="_blank"  class="text-decoration-none text-black link-primary">TRAN QUANG Thai-Son</a></p>
    </div>
  </div>
</div>
  </body>
</html>

app/views/lores/_form.html.erb
<%= simple_form_for(@lore) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-success' %>
  </div>
<% end %>
 

app/views/lores/_lore.html.erb
<div id="<%= dom_id lore %>">
  <p>
    <strong>Title:</strong>
    <%= lore.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= lore.content %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= lore.image %>
  </p>

</div>

app/views/lores/edit.html.erb
<h1>Editing lore</h1>

<%= render "form", lore: @lore %>

<br>

<div>
  <%= link_to "Show this lore", @lore, class:'btn btn-primary me-2 mb-5' %>
  <%= link_to "Back to lores", lores_path, class:'btn btn-primary me-2 mb-5' %>
</div>

app/views/lores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mb-5">Lore</h1>

<div id="lores" class="d-flex flex-column">
    <% @lores.each do |lore| %>
      <ul>
     <li><h3 class="mb-4"><%= link_to lore.title, lore, class:'text-decoration-none text-black link-primary' %></h3></li>
     </ul>
  <% end %>
</div>

<%= link_to "New lore", new_lore_path, class:'btn btn-primary mb-5 mt-5' %>

app/views/lores/new.html.erb
<h1>New lore</h1>

<%= render "form", lore: @lore, class:'btn btn-primary' %>
<br>

<div>
  <%= link_to "Back to lores",lores_path, class:'btn btn-primary' %>
</div>

app/views/lores/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card border-0 rounded-0 bg-light" style="max-width: 100%;">
  <div class="row g-0 d-flex justify-content-between">
    <div class="col-md-5">
      <img src="<%= @lore.image %>" class="img-fluid rounded mb-5">
    </div>
    <div class="col-md-5">
      <div class="card-body">
        <h2 class="card-title"><%= @lore.title %></h2>
        <p class="card-text">
          <%= @lore.content %>
        </p>
 
      </div>
    </div>
  </div>
</div>

<div>
  <%= link_to "Edit this lore", edit_lore_path(@lore), class:'btn btn-warning' %> 
  <%= link_to "Back to lores", lores_path, class:'btn btn-primary' %>

  <%= button_to "Destroy this lore", @lore, method: :delete, class:'btn btn-danger mt-2 mb-5' %>
</div>

app/views/parasites/_form.html.erb
<%= simple_form_for(@parasite) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :capacity %>
    <%= f.input :pv %>
    <%= f.input :atk %>
    <%= f.input :def %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-success' %>
  </div>
<% end %>

app/views/parasites/_parasite.html.erb
<div id="<%= dom_id parasite %>">
  <p>
    <strong>Name:</strong>
    <%= parasite.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= parasite.description %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= parasite.capacity %>
  </p>

  <p>
    <strong>Pv:</strong>
    <%= parasite.pv %>
  </p>

  <p>
    <strong>Atk:</strong>
    <%= parasite.atk %>
  </p>

  <p>
    <strong>Def:</strong>
    <%= parasite.def %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= parasite.image %>
  </p>

</div>

app/views/parasites/edit.html.erb
<h1>Editing parasite</h1>

<%= render "form", parasite: @parasite %>

<br>

<div>
  <%= link_to "Show this parasite", @parasite, class:'btn btn-primary me-2 mb-5' %> 
  <%= link_to "Back to parasites", parasites_path, class:'btn btn-primary me-2 mb-5' %>
</div>

app/views/parasites/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="mb-5">Parasites</h2>

<div id="parasites" class="container d-flex flex-wrap p-0 justify-content-evenly">
    <% @parasites.each do |parasite| %>

    <%= link_to(parasite, class:'link-dark text-decoration-none') do %>
        <div class="card shadow-sm mb-5 bg-body rounded-3 me-2 border border-success border-5 p-0" style="width:300px">
      <img src="<%= parasite.image %>" class="w-100 p-0 -object-fit-cover mx-auto img-fluid">
      <div class="card-body">
        <h5 class="card-title text-center"><%= parasite.name %></h5>
        <div class="h-2 w-50 p-1 bg-success rounded mt-4 mx-auto"></div>
        <div class="card-text mt-4 justify-content-around d-flex flex-row">
          <p>
            <strong>HP:</strong>
            <%= parasite.pv %>
          </p>
          <p>
            <strong>Atk:</strong>
            <%= parasite.atk %>
            <strong>Def:</strong>
            <%= parasite.def %>
          </p>
        </div>
      </div>
    </div>
<% end %>
    
  <% end %>
</div>

<%= link_to "New parasite", new_parasite_path, class:'btn btn-success rounded-2 mb-5' %>

app/views/parasites/new.html.erb
<h1>New parasite</h1>

<%= render "form", parasite: @parasite, class:'btn btn-primary' %>

<br>

<div>
  <%= link_to "Back to parasites", parasites_path, class:'btn btn-primary' %>
</div>

app/views/parasites/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card bg-light border border-0 rounded-0 mb-5" style="max-width: 100%;">
  <div class="row g-0 d-flex justify-content-between">
<div class="col-md-5">
      <img src="<%= @parasite.image %>" class="img-fluid rounded ">
    </div>
    <div class="col-md-5">
      <div class="card-body">
        <h3 class="card-title"><%= @parasite.name %></h5>
        <p class="card-text">
          <strong>Pv:</strong>
          <%= @parasite.pv %>
          <strong>Atk:</strong>
          <%= @parasite.atk %>
          <strong>Def:</strong>
          <%= @parasite.def %>
        </p>
        <h5 class="card-title">Description</h5>
        <p class="card-text"><%= @parasite.description %></p>
        <h5 class="card-title">Capacity</h5>
        <p class="card-text"><%= @parasite.capacity %></p>
      </div>
    </div>
  </div>
</div>

<div>
  <%= link_to "Edit this parasite", edit_parasite_path(@parasite), class:'btn btn-warning' %> 
  <%= link_to "Back to parasites", parasites_path, class:'btn btn-primary' %>

  <%= button_to "Destroy this parasite", @parasite, method: :delete, class:'btn btn-danger mt-2 mb-5' %>
</div>

app/views/plants/_form.html.erb
<%= simple_form_for(@plant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :capacity %>
    <%= f.input :pv %>
    <%= f.input :atk %>
    <%= f.input :def %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-success' %>
  </div>
<% end %>

app/views/plants/_plant.html.erb
<div id="<%= dom_id plant %>">
  <p>
    <strong>Name:</strong>
    <%= plant.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= plant.description %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= plant.capacity %>
  </p>

  <p>
    <strong>HP:</strong>
    <%= plant.pv %>
  </p>

  <p>
    <strong>Atk:</strong>
    <%= plant.atk %>
  </p>

  <p>
    <strong>Def:</strong>
    <%= plant.def %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= plant.image %>
  </p>

</div>

app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render "form", plant: @plant %>

<br>

<div>
  <%= link_to "Show this plant", @plant, class:'btn btn-primary me-2 mb-5' %> 
  <%= link_to "Back to plants", plants_path, class:'btn btn-primary me-2 mb-5' %>
</div>

app/views/plants/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="mb-5">Plants</h2>

<div id="plants" class="container d-flex flex-wrap p-0 justify-content-evenly">
    <% @plants.each do |plant| %>

    <%= link_to(plant, class:'link-dark text-decoration-none') do %>
        <div class="card shadow-sm mb-5 bg-body rounded-3 me-2 border border-success border-5 p-0" style="width:300px">
      <img src="<%= plant.image %>" class="w-100 p-0 -object-fit-cover mx-auto img-fluid">
      <div class="card-body">
        <h5 class="card-title text-center"><%= plant.name %></h5>
        <div class="h-2 w-50 p-1 bg-success rounded mt-4 mx-auto"></div>
        <div class="card-text mt-4 justify-content-around d-flex flex-row">
          <p>
            <strong>HP:</strong>
            <%= plant.pv %>
          </p>
          <p>
            <strong>Atk:</strong>
            <%= plant.atk %>
            <strong>Def:</strong>
            <%= plant.def %>
          </p>
        </div>
      </div>
    </div>
<% end %>
    
  <% end %>
</div>

<%= link_to "New plant", new_plant_path, class:'btn btn-success rounded-2 mb-5' %>

app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render "form", plant: @plant, class:'btn btn-primary' %>

<br>

<div>
  <%= link_to "Back to plants", plants_path, class:'btn btn-primary' %>
</div>

app/views/plants/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card bg-light border border-0 rounded-0 mb-5" style="max-width: 100%;">
  <div class="row g-0 d-flex justify-content-between">
<div class="col-md-5">
      <img src="<%= @plant.image %>" class="img-fluid rounded ">
    </div>
    <div class="col-md-5">
      <div class="card-body">
        <h3 class="card-title"><strong><%= @plant.name %></strong></h3>
        <p class="card-text">
          <strong>HP:</strong>
          <%= @plant.pv %>
          <strong>Atk:</strong>
          <%= @plant.atk %>
          <strong>Def:</strong>
          <%= @plant.def %>
        </p>
        <h4 class="card-title">Description :</h4>
        <p class="card-text"><%= @plant.description %></p>
        <h4 class="card-title">Capacity :</h4>
        <p class="card-text"><%= @plant.capacity %></p>
      </div>
    </div>
  </div>
</div>

<div>
  <%= link_to "Edit this plant", edit_plant_path(@plant), class:'btn btn-warning' %> 
  <%= link_to "Back to plants", plants_path, class:'btn btn-primary' %>

  <%= button_to "Destroy this plant", @plant, method: :delete, class:'btn btn-danger mt-2 mb-5' %>
</div>